# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_supportedFormats <- function() {
    .Call('rxylib_get_supportedFormats', PACKAGE = 'rxylib')
}

get_version <- function() {
    .Call('rxylib_get_version', PACKAGE = 'rxylib')
}

read_data <- function(path, format_name, options) {
    .Call('rxylib_read_data', PACKAGE = 'rxylib', path, format_name, options)
}

